/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Form.Customer_Form;

/**
 *
 * @author Admin
 */
public class AboutUs_Form extends javax.swing.JPanel {

    /**
     * Creates new form AboutUs_Form
     */
    public AboutUs_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new View.Swing.PanelRound();
        img = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        wel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        footer = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMember = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        header1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 222, 222));

        panelRound1.setBackground(new java.awt.Color(247, 247, 247));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/aboutus.jpg"))); // NOI18N

        header.setFont(new java.awt.Font("Papyrus", 1, 20)); // NOI18N
        header.setForeground(new java.awt.Color(108, 91, 123));
        header.setText("ABOUT US");

        wel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        wel.setForeground(new java.awt.Color(63, 63, 63));
        wel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wel.setText(
                "<html>  Welcome to  <i style=\"color:rgb(108,91,123);font-size:16px;\">  ROYAL THEDREAMERS<i> </html>");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt.setEditable(false);
        txt.setBackground(new java.awt.Color(255, 255, 255));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(89, 89, 89));
        txt.setLineWrap(true);
        txt.setRows(5);
        txt.setText(
                "Quán Bi-A là điểm đến lý tưởng cho những người yêu thích trò chơi bi-a, từ những người mới bắt đầu cho đến những cao thủ đã có kinh nghiệm. Với không gian rộng rãi và thoải mái, bạn có thể thư giãn và thưởng thức trò chơi cùng bạn bè hoặc gia đình.\r\n"
                        + //
                        "\r\n" + //
                        "Chúng tôi tự hào về các bàn bi-a chất lượng cao và đội ngũ nhân viên phục vụ chuyên nghiệp, luôn sẵn sàng đáp ứng mọi nhu cầu của quý khách. Không chỉ là nơi chơi bi-a, Quán Bi-A còn cung cấp các dịch vụ phục vụ đồ uống và đồ ăn ngon miệng, giúp bạn có thể thưởng thức trò chơi mà không phải lo lắng về gì khác.\r\n"
                        + //
                        "\r\n" + //
                        "Dù bạn đến để thư giãn sau một ngày làm việc căng thẳng, hoặc để thử thách kỹ năng bi-a của mình, Quán Bi-A luôn sẵn lòng chào đón bạn với không gian ấm áp và thân thiện. Hãy đến và trải nghiệm sự hứng khởi của trò chơi bi-a tại Quán Bi-A ngay hôm nay!");
        txt.setWrapStyleWord(true);
        txt.setBorder(null);
        txt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt.setFocusable(false);
        txt.setRequestFocusEnabled(false);
        txt.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(txt);

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        footer.setForeground(new java.awt.Color(63, 63, 63));
        footer.setText("Since : 2023 - Co-founder by The Dreamers Team\n");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setFocusable(false);

        listMember.setColumns(20);
        listMember.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        listMember.setForeground(new java.awt.Color(89, 89, 89));
        listMember.setRows(5);
        listMember.setText("Team Members :\n Nguyễn Quốc Trung - Developer\n Phùng Văn Nguyên -  Developer");
        listMember.setBorder(null);
        listMember.setFocusable(false);
        jScrollPane3.setViewportView(listMember);

        jSeparator1.setBackground(new java.awt.Color(76, 76, 76));

        header1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        header1.setForeground(new java.awt.Color(89, 89, 89));
        header1.setText("Tastes like a bit of heaven on your tongue.");
        header1.setToolTipText("");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
                panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelRound1Layout.createSequentialGroup()
                                                .addGroup(panelRound1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelRound1Layout.createSequentialGroup()
                                                                .addGap(236, 236, 236)
                                                                .addComponent(header))
                                                        .addGroup(panelRound1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addGroup(panelRound1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(wel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                550,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(footer)
                                                                        .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30,
                                                        Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout
                                                .createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(panelRound1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                panelRound1Layout.createSequentialGroup()
                                                                        .addComponent(jSeparator1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                470,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(75, 75, 75))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                panelRound1Layout.createSequentialGroup()
                                                                        .addComponent(header1)
                                                                        .addGap(116, 116, 116)))))
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 494,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)));
        panelRound1Layout.setVerticalGroup(
                panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(header)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(header1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(footer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(7, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea listMember;
    private View.Swing.PanelRound panelRound1;
    private javax.swing.JTextArea txt;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
